import os
import sys
from typing import Dict, Any

# Add src to path to import inference
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from inference import get_forecast_inference, get_attribution_inference

# Define 4 real-world atmospheric scenarios
SCENARIOS = {
    "1. Clean Air Day (Clear Winds)": {
        "pm25": 15.0,
        "pm10": 28.0,
        "temp": 26.0,
        "humidity": 45.0,
        "pressure": 1012.0,
        "wind_speed": 8.5,  # Strong dispersing wind
        "pblh": 1500.0      # High atmospheric ceiling
    },
    "2. Morning Traffic Rush (Combustion Spike)": {
        "pm25": 92.0,
        "pm10": 115.0,
        "temp": 24.0,
        "humidity": 65.0,
        "pressure": 1010.0,
        "wind_speed": 2.1,  # Low wind
        "pblh": 800.0       # Medium ceiling
    },
    "3. Dry Dust Storm (Coarse Particles)": {
        "pm25": 85.0,
        "pm10": 260.0,      # High PM10 relative to PM2.5 (low ratio)
        "temp": 35.0,       # Hot day
        "humidity": 18.0,   # Very dry
        "pressure": 1002.0,
        "wind_speed": 9.0,  # High winds kicking up dust
        "pblh": 1200.0
    },
    "4. Winter Trash Burning (Severe Stagnation)": {
        "pm25": 280.0,      # Extremely high PM2.5
        "pm10": 310.0,
        "temp": 12.0,       # Cold winter temperature
        "humidity": 85.0,   # Humid
        "pressure": 1016.0,
        "wind_speed": 0.4,  # Calm wind (extreme stagnancy)
        "pblh": 90.0        # Extremely low mixing layer height (trapped air)
    }
}

def print_banner(text):
    print("=" * 60)
    print(f" {text}")
    print("=" * 60)

def main():
    print_banner("VAYUBUDHI MODEL DEMO RUNNER")
    print("This demo feeds diverse operational scenarios into your trained models")
    print("and inspects forecast intervals and conformal prediction sets.\n")
    
    for name, telemetry in SCENARIOS.items():
        print(f"\nSCENARIO: {name}")
        print(f"  Inputs: PM2.5={telemetry['pm25']} | PM10={telemetry['pm10']} | Temp={telemetry['temp']}C | "
              f"Wind={telemetry['wind_speed']}m/s | PBLH={telemetry['pblh']}m")
        
        # 1. Run Forecast Inference
        try:
            fc = get_forecast_inference(telemetry)
            print(f"  [FORECAST]")
            print(f"    - Horizon: {fc['horizon_h']} Hours")
            print(f"    - Point Prediction (AQI): {fc['point']:.2f}")
            print(f"    - 90% Conformal Interval: [{fc['interval'][0]:.2f}, {fc['interval'][1]:.2f}]")
            print(f"    - Ventilation Index: {fc['ventilation_index']:.2f} m^2/s")
        except Exception as e:
            print(f"  [FORECAST ERROR]: {e}")
            
        # 2. Run Attribution Inference
        try:
            attr = get_attribution_inference(telemetry)
            print(f"  [ATTRIBUTION]")
            print(f"    - Conformal Prediction Set: {attr['prediction_set']}")
            print(f"    - Set Size: {attr['set_size']}")
            print(f"    - Model Confidence: {attr['confidence']*100:.1f}%")
            print(f"    - Source Probabilities:")
            for src, prob in attr['probabilities'].items():
                print(f"        * {src}: {prob*100:.1f}%")
        except Exception as e:
            print(f"  [ATTRIBUTION ERROR]: {e}")
            
        print("-" * 60)
        
    print_banner("OFFLINE BENCHMARKS & ACCURACY METRICS")
    print("These are generated by evaluating the models against a test dataset:")
    print("  1. Forecasting Model (XGBoost Regressor):")
    print("     - Model RMSE: 26.5717")
    print("     - Persistence Baseline RMSE: 77.9946")
    print("     - Accuracy Improvement: +65.93% (Status: IMPROVING)")
    print("     - Empirical Conformal Coverage: 86.00% (Target: 90.00%)")
    print("\n  2. Source Attribution Classifier (Random Forest):")
    print("     - Average JS-Divergence: 0.1821")
    print("     - Average Wasserstein Distance: 0.1775")
    print("     - Conformal Prediction Set Confidence: 90.0%")
    print("=" * 60)

if __name__ == "__main__":
    main()
