"""
SQLAlchemy database models for VayuBudhi.
Defines storage schema for sensor readings, ML model forecasts,
source attribution classifier results, optimized dispatch routes, and ROI calculations.
"""
from sqlalchemy import Column, Integer, String, Float, JSON, DateTime
from datetime import datetime
from app.database import Base

class SensorReading(Base):
    """
    Model for live weather/AQI sensor telemetry received from ESP32 station (Contract 1).
    """
    __tablename__ = "sensor_readings"

    id = Column(Integer, primary_key=True, index=True)
    station_id = Column(String, nullable=False, index=True)
    timestamp = Column(String, nullable=False)
    pm25 = Column(Float, nullable=False)
    pm10 = Column(Float, nullable=False)
    temp = Column(Float, nullable=False)
    humidity = Column(Float, nullable=False)
    pressure = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class Forecast(Base):
    """
    Model for 24h point and conformal interval forecast values (Contract 3).
    """
    __tablename__ = "forecasts"

    id = Column(Integer, primary_key=True, index=True)
    horizon_h = Column(Integer, nullable=False)
    point = Column(Float, nullable=False)
    interval = Column(JSON, nullable=False)  # Stores List[float], e.g., [180.0, 245.0]
    ventilation_index = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class AttributionResult(Base):
    """
    Model for source apportionment classifier prediction results (Contract 2).
    """
    __tablename__ = "attribution_results"

    id = Column(Integer, primary_key=True, index=True)
    prediction_set = Column(JSON, nullable=False)  # Stores List[str], e.g., ["biomass_burning"]
    set_size = Column(Integer, nullable=False)
    confidence = Column(Float, nullable=False)
    probabilities = Column(JSON, nullable=False)  # Stores Dict[str, float]
    created_at = Column(DateTime, default=datetime.utcnow)

class EnforcementRoute(Base):
    """
    Model for optimized inspect/patrol routing plans generated by OR-Tools (Contract 4).
    """
    __tablename__ = "enforcement_routes"

    id = Column(Integer, primary_key=True, index=True)
    route_id = Column(String, unique=True, index=True, nullable=False)
    stops = Column(JSON, nullable=False)  # Stores List[dict] representing stops
    created_at = Column(DateTime, default=datetime.utcnow)

class ROIResult(Base):
    """
    Model for cost-benefit ROI calculation details.
    """
    __tablename__ = "roi_results"

    id = Column(Integer, primary_key=True, index=True)
    route_id = Column(String, nullable=False, index=True)
    exposure_reduction = Column(Float, nullable=False)
    compliance_cost = Column(Float, nullable=False)
    roi = Column(Float, nullable=False)
    calculated_at = Column(DateTime, default=datetime.utcnow)
